[package]
name = "rust_resample"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_resample"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.18.3"
features = ["extension-module"]

[profile.release]
opt-level = "z"